### ISSUE TITLE
Looks like api.ipify.org is down?

### ISSUE THREAD

**Issue by cdrage** [AMilassin/docker-dodns#1]
Been getting this error lately (for I don't know how long however...)

Did yours recently stop working too @AMilassin ?

```
docker@server:~/do$ cat dodns.log 
ERR: { Error: getaddrinfo EAI_AGAIN api.ipify.org:443
    at Object.exports._errnoException (util.js:1016:11)
    at errnoException (dns.js:55:15)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:91:26)
  code: 'EAI_AGAIN',
  errno: 'EAI_AGAIN',
  syscall: 'getaddrinfo',
  hostname: 'api.ipify.org',
  host: 'api.ipify.org',
  port: 443 }
```

**Comment by cdrage** [comment]
Nevermind! Looks to have been a docker host bug... network randomly stopped within the docker container. I'm going to close this issue.

P.S. your docker container is awesome, it's in-use every day updating my rack server @ home :100:

**Comment by AMilassin** [comment]
Well, happy to help :D.
You can always test `api.ipify.org` by just calling manually from a browser.
